import React, { useEffect, useState } from 'react';
import AdminLayout from '../../layouts/AdminLayout.jsx';
import { apiRequest } from '../../services/api.js';
const configs={promotions:{fields:[['title','Judul','text',true],['description','Deskripsi','textarea'],['start_date','Tanggal mulai','date'],['end_date','Tanggal selesai','date'],['image','Banner','file'],['sort_order','Urutan','number']]},achievements:{fields:[['employee_name','Nama karyawan','text',true],['division','Divisi','text',true],['title','Achievement','text',true],['description','Deskripsi','textarea'],['achievement_date','Tanggal achievement','date',true],['image','Foto','file'],['sort_order','Urutan','number']]},hosts:{fields:[['name','Nama host','text',true],['photo','Foto host','file'],['sort_order','Urutan','number']]},channels:{fields:[['name','Nama divisi','text',true],['logo','Logo divisi','file'],['sort_order','Urutan','number']]},'weekly-meetings':{fields:[['name','Nama karyawan','text',true],['photo','Foto','file'],['sort_order','Urutan','number']]},
    birthdays:{fields:[['employee_name','Nama karyawan','text',true],['division','Divisi','text',true],['birth_date','Tanggal lahir','date',true],['image','Foto','file'],['sort_order','Urutan','number']]}};
const fileRules={
    promotions:{accept:'.jpg,.jpeg,.png,.webp,.gif,image/jpeg,image/png,image/webp,image/gif',hint:'JPG, PNG, WebP, atau GIF. Maksimal 50 MB.'},
    default:{accept:'.jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp',hint:'JPG, PNG, atau WebP. Maksimal 5 MB.'}};
const api=(resource)=>`/api/admin/${resource}`; const shownDate=(value)=>value?String(value).slice(0,10):'';
function Index({resource,title}) {
 const [records,setRecords]=useState({data:[],current_page:1,last_page:1,prev_page_url:null,next_page_url:null}),[error,setError]=useState(''),[notice,setNotice]=useState(()=>window.sessionStorage.getItem("cms-success")||''),[busy,setBusy]=useState(null),[page,setPage]=useState(1);
 async function load(){const query=new URLSearchParams({page:String(page)});try{const result=await apiRequest(`${api(resource)}?${query}`);setRecords(result);setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{if(notice)window.sessionStorage.removeItem("cms-success");},[]);useEffect(()=>{load();},[resource,page]);
 async function action(record,verb){if(verb==='DELETE'&&!window.confirm(`Hapus data ${record.title||record.employee_name||record.name}?`))return;setBusy(record.id);try{await apiRequest(`${api(resource)}/${record.id}${verb==='PATCH'?'/toggle':''}`,{method:verb});setNotice(verb==='DELETE'?'Data berhasil dihapus.':'Status data berhasil diperbarui.');await load();}catch(e){setError(e.message);}finally{setBusy(null);}}
 return <AdminLayout title={title}><div className="page-toolbar"><p className="muted">Kelola data {title.toLowerCase()} untuk papan informasi.</p><a className="button" href={`/admin/${resource}/create`}> Tambah data</a></div>{error&&<p className="notice notice-error" role="alert">{error}</p>}{notice&&<p className="notice notice-success" role="status">{notice}</p>}{records.data.length===0&&!error?<section className="empty-state"><span>CMS</span><h2>Belum ada data</h2><p>Tambahkan data pertama untuk mulai mengelola bagian ini.</p><a className="button" href={`/admin/${resource}/create`}>Tambah data</a></section>:records.data.length>0&&<><div className="table-wrap"><table><thead><tr><th>Konten</th><th>Tanggal</th><th>Status</th><th>Urutan</th><th>Aksi</th></tr></thead><tbody>{records.data.map(r=><tr key={r.id}><td><div className="record-cell">{r.image_url||r.photo_url||r.logo_url?<img className="record-thumb" src={r.image_url||r.photo_url||r.logo_url} alt=""/>:<span className="record-thumb placeholder">CMS</span>}<div><strong>{r.title||r.employee_name||r.name}</strong><small>{r.division||r.description||''}</small></div></div></td><td>{shownDate(r.start_date||r.achievement_date||r.date||r.birth_date)}{r.end_date&&`  ${shownDate(r.end_date)}`}</td><td><span className={`status-pill ${r.is_active?'active':'inactive'}`}>{r.is_active?'Aktif':'Nonaktif'}</span></td><td>{r.sort_order??''}</td><td><div className="row-actions"><a href={`/admin/${resource}/${r.id}/edit`}>Edit</a><button disabled={busy===r.id} onClick={()=>action(r,'PATCH')}>{r.is_active?'Nonaktifkan':'Aktifkan'}</button><button className="danger" disabled={busy===r.id} onClick={()=>action(r,'DELETE')}>Hapus</button></div></td></tr>)}</tbody></table></div><div className="pagination"><span>Halaman {records.current_page} dari {records.last_page} ({records.total} data)</span><div><button disabled={!records.prev_page_url} onClick={()=>setPage(page-1)}>Sebelumnya</button><button disabled={!records.next_page_url} onClick={()=>setPage(page+1)}>Berikutnya</button></div></div></>}</AdminLayout>;
}
function Form({resource,title,recordId}) {
 const fields=configs[resource]?.fields||[],fileRule=fileRules[resource]??fileRules.default;const [values,setValues]=useState({is_active:true,sort_order:0}),[errors,setErrors]=useState({}),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{if(recordId)apiRequest(`${api(resource)}/${recordId}`).then(data=>setValues({...data,start_date:data.start_date?.slice(0,10),end_date:data.end_date?.slice(0,10),achievement_date:data.achievement_date?.slice(0,10),birth_date:data.birth_date?.slice(0,10)})).catch(e=>setMessage(e.message));},[resource,recordId]);
 function change(name,value){setValues(v=>({...v,[name]:value}));setErrors(e=>({...e,[name]:null}));}
 async function submit(event){event.preventDefault();setSaving(true);setErrors({});setMessage('');const form=event.currentTarget,body=new FormData();fields.forEach(([name,,type])=>{if(type==='file'){if(form.elements[name].files[0])body.append(name,form.elements[name].files[0]);}else if(values[name]!==undefined&&values[name]!==null)body.append(name,values[name]);});body.append('is_active',values.is_active?'1':'0');try{await apiRequest(recordId?`${api(resource)}/${recordId}`:api(resource),{method:recordId?'PUT':'POST',body});window.sessionStorage.setItem("cms-success",recordId?"Perubahan berhasil disimpan.":"Data berhasil ditambahkan.");window.location.assign(`/admin/${resource}`);}catch(e){setErrors(e.errors||{});setMessage(e.message);}finally{setSaving(false);}}
 return <AdminLayout title={`${recordId?'Edit':'Tambah'} ${title}`}><div className="page-toolbar"><p className="muted">Lengkapi informasi konten di bawah ini.</p><a className="button button-light" href={`/admin/${resource}`}> Kembali</a></div>{message&&<p className="notice notice-error" role="alert">{message}</p>}<form className="content-form" onSubmit={submit}><div className="form-grid">{fields.map(([name,label,type,required])=><label className={type==='textarea'?'span-two':''} key={name}>{label}{type==='textarea'?<textarea rows="4" value={values[name]||''} onChange={e=>change(name,e.target.value)}/>:type==='file'?<><input type="file" name={name} accept={fileRule.accept}/><small>{fileRule.hint}</small>{values[`${name}_url`]&&<img className="form-preview" src={values[`${name}_url`]} alt="Preview gambar saat ini"/>}</>:<input type={type} required={required} min={type==='number'?'0':undefined} value={values[name]??''} onChange={e=>change(name,e.target.value)}/ >}{errors[name]&&<small className="field-error">{errors[name][0]}</small>}</label>)}<label className="checkbox-field"><input type="checkbox" checked={Boolean(values.is_active)} onChange={e=>change('is_active',e.target.checked)}/> Aktif</label></div><div className="form-actions"><button className="button" type="submit" disabled={saving}>{saving?'Menyimpan':'Simpan'}</button><a className="button button-light" href={`/admin/${resource}`}>Batal</a></div></form></AdminLayout>;
}
export function ResourcePage(props){return <Index {...props}/>;} export function ResourceFormPage(props){return <Form {...props}/>;}

